import { Router } from "express";
import authRoutes from "../modules/auth/auth";
import roomRoutes from "../modules/rooms/room.routes";
import reservationRoutes from "../modules/reservations/reservation.route";
import poolRoutes from "../modules/pool/pool.routes";
import maintenanceRoutes from "../modules/maintenance/maintenance.route";
import inventoryRoutes from "../modules/inventory/inventory.route";
import feedbackRoutes from "../modules/feedback/feedback.route";
import addonRoutes from "../modules/addons/addon.route";
import analyticsRoutes from "../modules/analytics/analytics.route";
import useroutes from "../modules/users/user.routes";
const router = Router();

router.use("/auth", authRoutes);
router.use("/rooms", roomRoutes);
router.use("/reservations", reservationRoutes);
router.use("/pool", poolRoutes);
router.use("/maintenance", maintenanceRoutes);
router.use("/inventory", inventoryRoutes);
router.use("/feedback", feedbackRoutes);
router.use("/addons", addonRoutes);
router.use("/analytics", analyticsRoutes);
router.use("/users", useroutes);
export default router;
